name: lesion-segmentor
services:
  lesion_segmentor:
    build:
      context: .
      dockerfile: Dockerfile
    image: lesion_segmentor:latest
    volumes:
      - ${INPUT_DIR:-/tmp}:/data/input
      - ${OUTPUT_DIR:-/tmp}:/data/output
      - ${MODEL_DIR:-~/.lesion_segmentor}:/root/.lesion_segmentor
    command: ["-i", "/data/input/$(INPUT_FILE)", "-o", "/data/output/$(OUTPUT_FILE)"]
    profiles: ["cpu"]  # Default profile

  lesion_segmentor_gpu:
    extends: lesion_segmentor
    image: lesion_segmentor:latest-gpu
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    profiles: ["gpu"] 