name: lesion-segmentor
services:
  lesion_segmentor:
    build:
      context: .
      dockerfile: Dockerfile
    image: lesion_segmentor:latest
    volumes:
      - "${INPUT_DIR}:/data/input"
      - "${OUTPUT_DIR}:/data/output"
      - "${MODEL_DIR:-~/.lesion_segmentor}:/root/.lesion_segmentor"
      - /Volumes:/Volumes
    command: ["-i", "/data/input/${INPUT_FILE}", "-o", "/data/output/${OUTPUT_FILE}", "--verbose"]
    tty: true
    stdin_open: true
    deploy:
      resources:
        limits:
          cpus: '0.8'
          memory: '80%'
        reservations:
          cpus: '0.5'
          memory: '50%'
    profiles: ["cpu"]

  lesion_segmentor_gpu:
    extends: lesion_segmentor
    image: lesion_segmentor:latest-gpu
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    profiles: ["gpu"] 