version: '3.8'

services:
  lesion-segmentor-cpu:
    platform: linux/arm64
    build:
      context: .
      dockerfile: Dockerfile
      args:
        TARGETPLATFORM: linux/arm64
    volumes:
      - type: bind
        source: ${INPUT_PATH}
        target: /app/input.nii.gz
        read_only: true
      - type: bind
        source: ${OUTPUT_PATH}
        target: /app/output.nii.gz
    command: ["--input", "/app/input.nii.gz", "--output", "/app/output.nii.gz"]
    profiles: ["cpu"]

  lesion-segmentor-gpu:
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile
      args:
        TARGETPLATFORM: linux/amd64
    volumes:
      - type: bind
        source: ${INPUT_PATH}
        target: /app/input.nii.gz
        read_only: true
      - type: bind
        source: ${OUTPUT_PATH}
        target: /app/output.nii.gz
    command: ["--input", "/app/input.nii.gz", "--output", "/app/output.nii.gz"]
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    profiles: ["gpu"] 